def on_button_pressed_a():
    if randint(0, 10) > 5:
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.ELECTRIC_SNARE)
        music.rest(music.beat(BeatFraction.WHOLE))
    else:
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.QUARTER))
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.QUARTER))
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.ACOUSTIC_SNARE)
        music.rest(music.beat(BeatFraction.QUARTER))
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_button_pressed_b():
    if randint(0, 10) > 5:
        midi.play_drum(DrumSound.ACOUSTIC_SNARE)
        music.rest(music.beat(BeatFraction.QUARTER))
        midi.play_drum(DrumSound.ACOUSTIC_SNARE)
        music.rest(music.beat(BeatFraction.QUARTER))
        midi.play_drum(DrumSound.ELECTRIC_SNARE)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.ACOUSTIC_BASS_DRUM)
        music.rest(music.beat(BeatFraction.QUARTER))
        midi.play_drum(DrumSound.ELECTRIC_SNARE)
        music.rest(music.beat(BeatFraction.QUARTER))
        midi.play_drum(DrumSound.HAND_CLAP)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.QUARTER))
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.QUARTER))
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.HAND_CLAP)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.ACOUSTIC_SNARE)
        music.rest(music.beat(BeatFraction.QUARTER))
        midi.play_drum(DrumSound.ELECTRIC_SNARE)
        music.rest(music.beat(BeatFraction.QUARTER))
    else:
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.ELECTRIC_SNARE)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.ACOUSTIC_SNARE)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.ELECTRIC_SNARE)
        music.rest(music.beat(BeatFraction.HALF))
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.QUARTER))
        midi.play_drum(DrumSound.ACOUSTIC_SNARE)
        music.rest(music.beat(BeatFraction.QUARTER))
        midi.play_drum(DrumSound.BASS_DRUM1)
        music.rest(music.beat(BeatFraction.HALF))
input.on_button_pressed(Button.B, on_button_pressed_b)

midi.use_raw_serial()

def on_forever():
    pass
basic.forever(on_forever)
